// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./components/Animation/Animation.vue')['default']
    DevBox: typeof import('./components/DevBox/DevBox.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RootComponent: typeof import('./components/RootComponent/RootComponent.vue')['default']
    SagaQrReader: typeof import('./components/SagaQrReader/SagaQrReader.vue')['default']
    ShowPowerName: typeof import('./components/ShowPowerName/ShowPowerName.vue')['default']
    Tutorial: typeof import('./components/Tutorial/Tutorial.vue')['default']
    Unpause: typeof import('./components/Unpause/Unpause.vue')['default']
  }
}

export { }
